/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package uk.ac.uea.cmp.srnaworkbench.viewers;

import java.util.HashMap;
import java.util.Map.Entry;
import javax.swing.JPanel;
import org.jfree.chart.ChartPanel;
import uk.ac.uea.cmp.srnaworkbench.GUIInterface;
import uk.ac.uea.cmp.srnaworkbench.MDIDesktopPane;
import uk.ac.uea.cmp.srnaworkbench.tools.ToolManager;
import uk.ac.uea.cmp.srnaworkbench.tools.qualitycheck.ma.MAList;
import uk.ac.uea.cmp.srnaworkbench.utils.AppUtils;

/**
 *
 * @author Matt
 */
public class MAgridViewer extends javax.swing.JInternalFrame implements GUIInterface
{
  /**
   * Creates new form MAgridViewer
   */
  public MAgridViewer(HashMap<String, HashMap<String, MAList>> maDataMap)
  {
    initComponents();
    //this.getLayout();
    for (Entry<String, HashMap<String, MAList>> e : maDataMap.entrySet())
    {
      String xSample = e.getKey();
      for (Entry<String, MAList> y : e.getValue().entrySet())
      {
        String ySample = y.getKey();
        MAplot maChart = new MAplot();
        maChart.inputData( y.getValue() );
        ChartPanel cp = maChart.getChartPanel();
        this.add( cp );
      }
    }
  }
  
  public static MAgridViewer generateMAgrid(HashMap<String, HashMap<String, MAList>> maDataMap)
  {
    
    final MAgridViewer newInstance = new MAgridViewer(maDataMap);
    javax.swing.SwingUtilities.invokeLater( new Runnable()
    {
      @Override
      public void run()
      {
        // Add VisSR to the desktop pane...
        MDIDesktopPane pane = AppUtils.INSTANCE.getMDIDesktopPane();

        if ( pane != null )
        {
          pane.add( newInstance );
        }

        ToolManager.getInstance().addTool( newInstance );

      }
    } );
    return newInstance;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    getContentPane().setLayout(new java.awt.GridLayout());

    pack();
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

  @Override
  public void runProcedure()
  {
    //throw new UnsupportedOperationException( "Not supported yet." ); //To change body of generated methods, choose Tools | Templates.
  }

  @Override
  public JPanel getParamsPanel()
  {
    throw new UnsupportedOperationException( "Not supported yet." ); //To change body of generated methods, choose Tools | Templates.
  }

  @Override
  public void setShowingParams( boolean newState )
  {
    throw new UnsupportedOperationException( "Not supported yet." ); //To change body of generated methods, choose Tools | Templates.
  }

  @Override
  public boolean getShowingParams()
  {
    throw new UnsupportedOperationException( "Not supported yet." ); //To change body of generated methods, choose Tools | Templates.
  }

  @Override
  public void shutdown()
  {
    throw new UnsupportedOperationException( "Not supported yet." ); //To change body of generated methods, choose Tools | Templates.
  }
}
