/*
 * ChooseDataDialog.java
 *
 * Created on 10-May-2011, 16:55:40
 */

package uk.ac.uea.cmp.srnaworkbench.tools.paresnip;

import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 *
 * @author Leighton
 */
public class ChooseDataDialog extends javax.swing.JDialog {

    private final String sPrefix = "Small RNA File: ";
    private final String dPrefix = "Degradome File: ";
    private final String tPrefix = "Transcripts File: ";
    private final String gPrefix = "Genome File: ";


    private File srnaome;
    private String sName;
    private File transcriptome;
    private String tName;
    private File degradome;
    private String dName;
    private File genome;
    private String gName;


    /** Creates new form ChooseDataDialog */
    public ChooseDataDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JLabel label = new JLabel("<html> Open Files:"
                                     + "<br/> Please select the appropriate"
                                     + "<br/> radio button in the top left"
                                     + "<br/> corner and then select the"
                                     + "<br/> appropriate file.");
        label.setBorder(BorderFactory.createTitledBorder("Information"));
        fileChooser.setAccessory(label);
    }

    public File getSrnaome(){
        return this.srnaome;
    }

    public File getDegradome(){
        return this.degradome;
    }

    public File getTranscriptome(){
        return this.transcriptome;
    }
    public File getGenome(){
        return this.genome;
    }

    /** This method is called from within the constructor to
     * initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filesSelectionButtonGroup = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        srnaRadioButton = new javax.swing.JRadioButton();
        degradomeRadioButton = new javax.swing.JRadioButton();
        transcriptomeRadioButton = new javax.swing.JRadioButton();
        genomeRadioButton = new javax.swing.JRadioButton();
        selectedFilesList = new java.awt.List();
        removeFile = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose Data");

        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("File Data Type"));

        filesSelectionButtonGroup.add(srnaRadioButton);
        srnaRadioButton.setSelected(true);
        srnaRadioButton.setText("Small RNAs");

        filesSelectionButtonGroup.add(degradomeRadioButton);
        degradomeRadioButton.setText("Degradome");

        filesSelectionButtonGroup.add(transcriptomeRadioButton);
        transcriptomeRadioButton.setText("Transcripts");
        transcriptomeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transcriptomeRadioButtonActionPerformed(evt);
            }
        });

        filesSelectionButtonGroup.add(genomeRadioButton);
        genomeRadioButton.setText("Genome (optional)");
        genomeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genomeRadioButtonActionPerformed(evt);
            }
        });

        removeFile.setText("Remove");
        removeFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srnaRadioButton)
                    .addComponent(degradomeRadioButton)
                    .addComponent(transcriptomeRadioButton)
                    .addComponent(genomeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedFilesList, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeFile, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectedFilesList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(srnaRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(degradomeRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transcriptomeRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genomeRadioButton))
                    .addComponent(removeFile, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fileChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doneButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFile(File f){
        if(this.srnaRadioButton.isSelected()){
            if(srnaome != null){
                selectedFilesList.remove(sName);
            }
            srnaome = f;
            sName = sPrefix+f.getName();
            selectedFilesList.add(sName);
        }else if(this.degradomeRadioButton.isSelected()){
            if(degradome != null){
                selectedFilesList.remove(dName);
            }
            degradome = f;
            dName = dPrefix+f.getName();
            selectedFilesList.add(dName);
        }else if(transcriptomeRadioButton.isSelected()){
            if(transcriptome != null){
                selectedFilesList.remove(tName);
            }
            transcriptome = f;
            tName = tPrefix+f.getName();
            selectedFilesList.add(tName);
        }else if(genomeRadioButton.isSelected()){
            if(genome != null){
                selectedFilesList.remove(gName);
            }
            this.genome = f;
            gName = gPrefix+f.getName();
            this.selectedFilesList.add(gName);
        }
    }

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        if(evt.getActionCommand().equalsIgnoreCase(JFileChooser.APPROVE_SELECTION)){
            if(fileChooser.getSelectedFile() != null){
                addFile(fileChooser.getSelectedFile());
            }
        }
        if(evt.getActionCommand().equalsIgnoreCase(JFileChooser.CANCEL_SELECTION)){
            this.setVisible(false);
        }
    }//GEN-LAST:event_fileChooserActionPerformed

    private void removeFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFileActionPerformed
        String selectedItem = selectedFilesList.getSelectedItem();
        if(selectedItem != null){
            selectedFilesList.remove(selectedItem);
            if(selectedItem.startsWith(sPrefix)){
                sName = null;
                srnaome = null;
            }else if(selectedItem.startsWith(dPrefix)){
                dName = null;
                degradome = null;
            }else if(selectedItem.startsWith(tPrefix)){
                tName = null;
                transcriptome = null;
            }else if(selectedItem.startsWith(gPrefix)){
                gName = null;
                genome = null;
            }
        }
    }//GEN-LAST:event_removeFileActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_doneButtonActionPerformed

    private void genomeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genomeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genomeRadioButtonActionPerformed

    private void transcriptomeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transcriptomeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transcriptomeRadioButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton degradomeRadioButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.ButtonGroup filesSelectionButtonGroup;
    private javax.swing.JRadioButton genomeRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton removeFile;
    private java.awt.List selectedFilesList;
    private javax.swing.JRadioButton srnaRadioButton;
    private javax.swing.JRadioButton transcriptomeRadioButton;
    // End of variables declaration//GEN-END:variables

}
