/*
 * AdapterRemoverMainFrame.java
 *
 * Created on 09-May-2011, 13:20:22
 */

package uk.ac.uea.cmp.srnaworkbench.tools.adaptorremover;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map.Entry;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.io.FilenameUtils;


import uk.ac.uea.cmp.srnaworkbench.GUIInterface;
import uk.ac.uea.cmp.srnaworkbench.help.JHLauncher;
import uk.ac.uea.cmp.srnaworkbench.tools.ToolHost;
import uk.ac.uea.cmp.srnaworkbench.utils.GoController;
import uk.ac.uea.cmp.srnaworkbench.utils.StatusTracker;


import static org.apache.commons.io.IOUtils.DIR_SEPARATOR;
import static org.apache.commons.io.IOUtils.LINE_SEPARATOR;
import uk.ac.uea.cmp.srnaworkbench.tools.filter.FilterStage;

import static uk.ac.uea.cmp.srnaworkbench.utils.LOGGERS.WorkbenchLogger.LOGGER;
import uk.ac.uea.cmp.srnaworkbench.utils.Tools;
import uk.ac.uea.cmp.srnaworkbench.viewers.AbundanceDistributionViewer;

/**
 * Housing for an AR_ResultsPanel, an AdaptorRemoverPanel GUI and some execution controls
 * @author w0445959
 */
public final class AdaptorRemoverMainFrame extends javax.swing.JInternalFrame implements GUIInterface, ToolHost
{
  // GUI engine
  HashMap<String, AdaptorRemoverRunner> ar_runners = new HashMap<String, AdaptorRemoverRunner>();
  
  // GUI vars
  private GoController go_control;
  private AdaptorRemoverInputPanel ar_input;
  private AdaptorRemoverResultsPanel ar_output;
  private ArrayList<File> in_files;
  private boolean filesIgnored;
  private int showingAbundancePlots = JOptionPane.NO_OPTION;
  private boolean streamMode;
 
  public AdaptorRemoverMainFrame(boolean streamMode)
  {
    
    this();
    //set stream mode after call to default constructor as this sets stream mode to false
    this.streamMode = streamMode;
  }
  /** Creates new form AdaptorRemoverMainFrame */
  public AdaptorRemoverMainFrame()
  {
    initComponents();

    streamMode = false;
    //ar_runner = new AdaptorRemoverRunner(this);
    
    ar_output = new AdaptorRemoverResultsPanel();

    ar_input = new AdaptorRemoverInputPanel();
    ar_input.setVisible( true );
    ar_input.setEnabled( true );

    javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout( pnlInput );
    pnlInput.setLayout( mainPanelLayout );
    mainPanelLayout.setHorizontalGroup(
      mainPanelLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 648, Short.MAX_VALUE ).addComponent( ar_input ) );
    mainPanelLayout.setVerticalGroup(
      mainPanelLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 301, Short.MAX_VALUE ).addComponent( ar_input ) );


    javax.swing.GroupLayout resultsPanelLayout = new javax.swing.GroupLayout( pnlResults );
    pnlResults.setLayout( resultsPanelLayout );
    resultsPanelLayout.setHorizontalGroup(
      resultsPanelLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 648, Short.MAX_VALUE ).addComponent( ar_output ) );
    resultsPanelLayout.setVerticalGroup(
      resultsPanelLayout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGap( 0, 125, Short.MAX_VALUE ).addComponent( ar_output ) );

    pack();

    JHLauncher.setupContextDependentHelp( "HTML_ad_rem_html", mnuHelpContents, this.getRootPane() );
    
    this.go_control = new GoController( this.cmdStart, this.cmdCancel, this.mnuRunStart, this.mnuRunCancel );
    

    Tools.trackPage("Adapter Removal Main GUI Frame Load");
    
   

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pnlInput = new javax.swing.JPanel();
        pnlResults = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cmdCancel = new javax.swing.JButton();
        AR_ProgressBar = new javax.swing.JProgressBar();
        lblStatus = new javax.swing.JLabel();
        cmdStart = new javax.swing.JButton();
        mnuMain = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuFileExit = new javax.swing.JMenuItem();
        mnuRun = new javax.swing.JMenu();
        mnuRunStart = new javax.swing.JMenuItem();
        mnuRunCancel = new javax.swing.JMenuItem();
        mnuRunSep1 = new javax.swing.JPopupMenu.Separator();
        mnuRunReset = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuHelpContents = new javax.swing.JMenuItem();

        setBackground(new java.awt.Color(120, 120, 120));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Adaptor Remover");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GUI_Icons/scissors.jpg"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener()
        {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt)
            {
                closingMainFrame(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
        });

        jPanel1.setBackground(new java.awt.Color(120, 120, 120));

        pnlInput.setBackground(new java.awt.Color(120, 120, 120));
        pnlInput.setMinimumSize(new java.awt.Dimension(750, 450));
        pnlInput.setPreferredSize(new java.awt.Dimension(750, 450));

        javax.swing.GroupLayout pnlInputLayout = new javax.swing.GroupLayout(pnlInput);
        pnlInput.setLayout(pnlInputLayout);
        pnlInputLayout.setHorizontalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlInputLayout.setVerticalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );

        pnlResults.setBackground(new java.awt.Color(120, 120, 120));
        pnlResults.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Results", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans Unicode", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout pnlResultsLayout = new javax.swing.GroupLayout(pnlResults);
        pnlResults.setLayout(pnlResultsLayout);
        pnlResultsLayout.setHorizontalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
        );
        pnlResultsLayout.setVerticalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(120, 120, 120));

        cmdCancel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        cmdCancel.setText("Cancel");
        cmdCancel.setToolTipText("<html> Cancel process. </html>");
        cmdCancel.setEnabled(false);
        cmdCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmdCancelActionPerformed(evt);
            }
        });

        lblStatus.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("Status: ");

        cmdStart.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        cmdStart.setText("Start");
        cmdStart.setToolTipText("<html> Start processing. </html>");
        cmdStart.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmdStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AR_ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cmdStart, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AR_ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel)
                    .addComponent(cmdStart))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInput, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInput, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        mnuMain.setBackground(new java.awt.Color(213, 219, 245));

        mnuFile.setText("File");

        mnuFileExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SharedImages/close-tool.png"))); // NOI18N
        mnuFileExit.setText("Close");
        mnuFileExit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuFileExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFileExit);

        mnuMain.add(mnuFile);

        mnuRun.setText("Run");

        mnuRunStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SharedImages/light.png"))); // NOI18N
        mnuRunStart.setText("Start");
        mnuRunStart.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuRunStartActionPerformed(evt);
            }
        });
        mnuRun.add(mnuRunStart);

        mnuRunCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SharedImages/lightCancel.png"))); // NOI18N
        mnuRunCancel.setText("Cancel");
        mnuRunCancel.setEnabled(false);
        mnuRunCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuRunCancelActionPerformed(evt);
            }
        });
        mnuRun.add(mnuRunCancel);
        mnuRun.add(mnuRunSep1);

        mnuRunReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SharedImages/reload.png"))); // NOI18N
        mnuRunReset.setText("Reset");
        mnuRunReset.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuRunResetActionPerformed(evt);
            }
        });
        mnuRun.add(mnuRunReset);

        mnuMain.add(mnuRun);

        mnuHelp.setText("Help");

        mnuHelpContents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SharedImages/lookup.png"))); // NOI18N
        mnuHelpContents.setText("Contents");
        mnuHelp.add(mnuHelpContents);

        mnuMain.add(mnuHelp);

        setJMenuBar(mnuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdStartActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmdStartActionPerformed
    {//GEN-HEADEREND:event_cmdStartActionPerformed
      runProcedure();
    }//GEN-LAST:event_cmdStartActionPerformed

    private void closingMainFrame(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_closingMainFrame
    {//GEN-HEADEREND:event_closingMainFrame
      for ( Entry<String, AdaptorRemoverRunner> entry : ar_runners.entrySet() )
      {
        entry.getValue().cancel();
      }
      //Tools.stopTracking(  );
    }//GEN-LAST:event_closingMainFrame

private void mnuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFileExitActionPerformed
  this.setVisible( false );
  this.dispose();
}//GEN-LAST:event_mnuFileExitActionPerformed

private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
  for ( Entry<String, AdaptorRemoverRunner> entry : ar_runners.entrySet() )
      {
        entry.getValue().cancel();
      }
}//GEN-LAST:event_cmdCancelActionPerformed

private void mnuRunStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRunStartActionPerformed
  

  this.runProcedure();
}//GEN-LAST:event_mnuRunStartActionPerformed

private void mnuRunCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRunCancelActionPerformed
  for ( Entry<String, AdaptorRemoverRunner> entry : ar_runners.entrySet() )
      {
        entry.getValue().cancel();
      }
}//GEN-LAST:event_mnuRunCancelActionPerformed

@Override
  public void shutdown()
  {
   this.setVisible( false );
  this.dispose();
  }
  private void mnuRunResetActionPerformed( java.awt.event.ActionEvent evt )//GEN-FIRST:event_mnuRunResetActionPerformed
  {//GEN-HEADEREND:event_mnuRunResetActionPerformed
    reset();
  }//GEN-LAST:event_mnuRunResetActionPerformed

  
  private void reset()
  {
    //this.ar_runner = new AdaptorRemoverRunner(this);
    ar_runners.clear();
    
    this.ar_input.reset();
    this.ar_output.reset();    
  }
  
  
  // ***** Start GUIInterface methods *****

  @Override
  public void runProcedure()
  {

    showAbundancePlot();
    filesIgnored = false;
    in_files = ar_input.getInputFiles();
    File out_dir = ar_input.getOutputDir();
    //StatusTracker statusTracker = new StatusTracker( AR_ProgressBar, lblStatus );
    if(!in_files.isEmpty())
    {
      lblStatus.setText( "Status: Processing..." );
      AR_ProgressBar.setMaximum( in_files.size() );
      Iterator<File> iterator = in_files.iterator();
      while ( iterator.hasNext() )
      {
        File theInput = iterator.next();
        //filename we will be creating in the filter tool:
        String singleOutPath = out_dir.getAbsolutePath() + DIR_SEPARATOR + FilenameUtils.removeExtension( theInput.getName() ) + "_AR.fa";
        File outputFile = new File( singleOutPath );
        //check for exist and do not overwrite unless told to:
        if ( outputFile.exists() )
        {
          if ( !this.ar_input.getOverwriteConfirm() )
          {
            filesIgnored = true;
            iterator.remove();
            LOGGER.log( Level.WARNING, "{0} not processed due to overwrite warning", outputFile.getName() );
            this.AR_ProgressBar.setMaximum( in_files.size() );
          }
        }

      }
      for ( File theInput : in_files )
      {
        AdaptorRemoverRunner adaptorRemoverRunner = new AdaptorRemoverRunner( this, showingAbundancePlots, streamMode );

        ar_output.addOutputTab( theInput.getName() );
        ar_output.setOutputLengthDistTabWaiting( theInput.getName(), true );
        ar_output.setOutputStatsTabWaiting( theInput.getName(), true );
        AdaptorRemoverParams ar_params = ar_input.getParams();
        adaptorRemoverRunner.runAdaptorRemover( theInput, out_dir, ar_params, null );
        ar_runners.put( theInput.getName(), adaptorRemoverRunner );
      }
      ar_output.revalidate();
      if ( filesIgnored )
      {
        JOptionPane.showMessageDialog( this,
          "Some files were ignored due to overwrite warnings" + LINE_SEPARATOR
          + "Re-run with force overwrite selected or choose an empty directory" + LINE_SEPARATOR
          + "Visit the log file for a list of all files that were not processed",
          "Output Warning",
          JOptionPane.ERROR_MESSAGE );
      }
    }
    else
    {
      JOptionPane.showMessageDialog( this,
          "No input files found",
          "Process Cancelled",
          JOptionPane.ERROR_MESSAGE );
    }
    
  }
  
  public void showAbundancePlot()
  {
    showingAbundancePlots = JOptionPane.showConfirmDialog(
                              this,
                              "Would you like to view the abundance plots for your data?",
                              "Adapter Removal",
                              JOptionPane.YES_NO_OPTION );
  }

  @Override public JPanel getParamsPanel()                       {return null;}
  @Override public void setShowingParams( boolean newState ){}
  @Override public boolean getShowingParams()               {return false;}

  // ***** End GUIInterface methods *****

  
  // ***** Start ToolHost methods *****
  
  @Override
  public void update()
  {    
    try
    {
      
      File out_dir = ar_input.getOutputDir();
      final ArrayList<String> historyWrite = new ArrayList<String>();
      boolean allComplete = true;
      for(final File theInput : in_files)
      {
        final AdaptorRemoverRunner getTrigger = ar_runners.get( theInput.getName() );
        if ( getTrigger.isComplete() )
        {
          historyWrite.add( out_dir.getAbsolutePath() + DIR_SEPARATOR + FilenameUtils.removeExtension( theInput.getName() ) + "_AR.fa" );

          lblStatus.setText( "Status: Completed: " + theInput.getName() );
          AR_ProgressBar.setValue( AR_ProgressBar.getValue() + 1 );
          ar_output.fillLengthDistTable( theInput.getName(), getTrigger.getLengths() );
          List<FilterStage> results = getTrigger.getResults();
          ar_output.fillExecutionStatsTable( theInput.getName(), getTrigger.getResults() );
          ar_output.setOutputLengthDistTabWaiting( theInput.getName(), false );
          ar_output.setOutputStatsTabWaiting( theInput.getName(), false );

        }
      }
      for(final File theInput : in_files)
      {
        AdaptorRemoverRunner getTrigger = ar_runners.get( theInput.getName() );
        if ( !getTrigger.isComplete() )
        {
          allComplete = false;
        }
      }
      //just give java a minute to think about swinging...
      Thread.sleep( 500 );
      if ( allComplete )
      {
        SwingUtilities.invokeLater( new Runnable()
        {
          @Override
          public void run()
          {
            lblStatus.setText( "Status: All Files Completed Successfully" );
            AR_ProgressBar.setValue( 0 );
            ar_input.addToHistory(historyWrite);
          }
        } );
      }
    }
    catch (Exception e)
    {
      showErrorDialog( e.getMessage() );
    }
  }
  
  @Override
  public void setRunningStatus( boolean running )
  {
    if ( this.go_control != null )
    {
      this.go_control.setRunning( running );
      this.ar_input.setEnabled( !running );
      this.mnuRunReset.setEnabled( !running );
    }
  }
  
  @Override
  public void showErrorDialog(String message)
  {
    JOptionPane.showMessageDialog( this,
        message,
        "Adaptor Remover Error",
        JOptionPane.ERROR_MESSAGE );
  }
  
  // ***** End HostTool methods *****
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar AR_ProgressBar;
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdStart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuFileExit;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuHelpContents;
    private javax.swing.JMenuBar mnuMain;
    private javax.swing.JMenu mnuRun;
    private javax.swing.JMenuItem mnuRunCancel;
    private javax.swing.JMenuItem mnuRunReset;
    private javax.swing.JPopupMenu.Separator mnuRunSep1;
    private javax.swing.JMenuItem mnuRunStart;
    private javax.swing.JPanel pnlInput;
    private javax.swing.JPanel pnlResults;
    // End of variables declaration//GEN-END:variables
}
